

tabPanel("Resumen General", fluidRow(
  headerPanel("Comportamiento de las Entidades que Transan en el Sistema Nacional de Compras y Contrataciones Públicas"),
column(width=9,
fluidRow(box(width = 12,tabsetPanel(type = "tabs",
                             tabPanel(title = "Gráfico por Unidades de Compra", 
                                      highchartOutput(outputId ="adjudicaciones_unidades", height = "650px"),
                                      h3("Tabla de Datos",align="center"),
                                      DT::dataTableOutput("table888")),
                             tabPanel(title= "Vista Historica",
                                      box(width=12, solidHeader = TRUE,status="info", title= "Seleccione la Unidad de Compra:",
                                          selectInput(inputId="UNIDADES",
                                                      label=NULL,
                                                      choices=levels(as.factor(data_unidad$UNIDAD_COMPRA)),
                                                      multiple =TRUE,
                                                      selected="ministerio de educacion")), br(),
                                      highchartOutput("historicos", height = "650px")),
                             tabPanel(title="Análisis de Modalidad de Compra",
                                      fluidRow(box(width=12, solidHeader = TRUE,status="info", title= "Seleccione la Unidad de Compra:",
                                          selectInput(inputId="unidad747",
                                                      label=NULL,
                                                      choices=levels(as.factor(data_modalidadv2$UNIDAD_COMPRA2)),
                                                      multiple =FALSE,
                                                      selected="ministerio de educacion"),
                                          selectInput(inputId="periodoanalisis",
                                                      label= NULL, 
                                                      choices = levels(as.factor(data_modalidadv2$gestion)),
                                                      selected= "2019"))), br(),
                                      highchartOutput("modalidad_desglose9898", height = "650px"), br(), br(),
                                      DT::dataTableOutput("tabla666")), 
                             tabPanel(title= "Análisis a Nivel de Contratos", 
                                      selectInput(inputId = 'modalidadcontratos',
                                                  label = 'Modalidad de Compra:',
                                                  multiple =TRUE,
                                                  choices= levels(as.factor(data_uc282$MODALIDAD_2)),
                                                  selected="licitacion publica"),
                                      h3("Grafico de Dispersion"),
                                      plotOutput('grafico_desglosecontratos', brush="plot_brush2"),
                                      h3("Tabla de Datos"), 
                                      DT:: dataTableOutput(outputId= "tabla_contratos")),
                             tabPanel(title="Comportamiento General Relativo",
                                      br(),
                                      splitLayout(selectInput(inputId = 'periodo6033',
                                                  label = 'Periodo',
                                                  choices= levels(as.factor(segmentacion_unidad2$gestion)),
                                                  selected="contratos"),
                                      selectInput(inputId = 'xcol',
                                                  label = 'Variable X',
                                                  choices= names(segmentacion_unidad2)[3:11],
                                                  selected="contratos"),
                                      selectInput(inputId = 'ycol',
                                                  label = 'Variable Y',
                                                  choices= names(segmentacion_unidad2)[3:11],
                                                  selected="proveedores_distintos"),
                                      numericInput(inputId ='clusters',
                                                  label= 'Clusters:',3,
                                                  min = 1, max = 9)),
                                      br(),
                                      plotOutput('plot1', brush="plot_brush"),
                                      h4(textOutput("description")),
                                      h3("Tabla de Datos"), 
                                      DT:: dataTableOutput(outputId= "info"))
                             
                             )))),
box(width=3, status="danger", solidHeader=TRUE, 
    title="Analisis de Genero",
    radioButtons(inputId = "GENERO", label="Seleccione el Género:",
                 choices= c("Femenino"= "0",
                            "Masculino, Femenino y No Especificado"="1"), 
                 selected = "1"),
    h6("Notas:", br(), "- Todos los datos del aplicativo cambian al género seleccionado",align="left")),
box(width=3, status="primary", solidHeader = TRUE, 
    title= "Seleccione las Categorías de Interés:",
    selectInput(inputId="indicador",
                label="Seleccione el indicador:",
                choices= c("Total Adjudicado"= "total_adjudicado",
                           "Cantidad de Contratos" ="contratos",
                           "Proveedores Distintos Adjudicados"="proveedores_distintos_adjudicados"),
                selected="total_adjudicado"),
    selectInput(inputId="gestion",
                label="Seleccione el Periodo:",
                choices= c("2018", "2019","2020"),
                multiple =TRUE,
                selected="2020"),
    h6("Notas:", br(), "- Cuando se seleccionan varios anos las cifras en el aplicativo se presentan acumuladas", br(),
       br (),"- Última actualización de los datos: Junio 2020",align="left")),
box(width=3, highchartOutput("grafico_pie"))))