


tabPanel("Stock Analysis", fluidRow(
  headerPanel('Exploratory Stock Analysis'),
  column(width=9,
         fluidRow(box(width = 12,tabsetPanel(type = "tabs",
                                             tabPanel(title = "Stock Chart", 
                                                      fluidPage(splitLayout(radioButtons(inputId = "charttype", label = strong("Chart Type:"),
                                                                      choices = c("line", "column"),
                                                                      selected = "column", inline=TRUE),
                                                                radioButtons(inputId= "variable", label= strong("Variable"),
                                                                       choices= c("Daily Prices",
                                                                                  "Monthly Prices",
                                                                                  "Monthly Returns"),
                                                                       selected= "Daily Prices", inline=TRUE)),
                                                      highchartOutput(outputId ="stockreturns_chart", height = "650px"),
                                                      DT::dataTableOutput(outputId = "SUMTABLE"),
                                                      verbatimTextOutput(outputId= "res")
                                                      )),
                                             tabPanel(title= "Histogram",
                                                      splitLayout(highchartOutput("histogram", height = "650px"),
                                                                  highchartOutput("histogram2", height = "650px")),
                                                      DT::dataTableOutput(outputId = "SUMTABLE2"),
                                                      br(),
                                                      h2("DrawDowns Analysis"),
                                                      plotlyOutput(outputId = "DrawdownsPlot"),
                                                      br(),
                                                      DT::dataTableOutput(outputId = "table958")),
                                             tabPanel(title="Correlation Analysis",
                                                      highchartOutput("scatterplot3030", height = "650px")))))),
    box(width=3, status="primary", solidHeader = TRUE, 
        selectizeInput(inputId = "sector", label = strong("Company Sector:"),
                  choices = levels(as.factor(ticker_source$Category)),
                  multiple = TRUE, 
                  selected = c("Energy", "Technology", "Capital Goods"),
                  options = list(maxItems = 10)),
      uiOutput("stockssymbols"),
      dateRangeInput(inputId = 'periodo',
                     label = strong('Date Range:'),
                     start= "2015-01-01",
                     end= Sys.Date(),
                     format= "yyyy-mm-dd",
                     separator= " - "), 
      selectInput(inputId="riskfree", 
                  label= strong("Select Risk Free IR:"),
                  choices=c("13 Week Treasury Bill",
                            "3-Month Treasury Constant Maturity Rate")),
      numericInput(inputId = "confidencelevel", label = strong("Confidence Level:"),
                   value= 0.5,
                   min=0.01, 
                   max=0.15,
                   step=0.05),
      actionButton(inputId="getquery", label="Get Info"),
      DT::dataTableOutput(outputId = "table1"))))
