
box(width=3, status="danger", solidHeader=TRUE, 
    title="Select the Categories for the Scatter Plot",
    selectizeInput(inputId="xaxis",  
                   label= "X-axis Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="NGDPDPC1"),
    selectizeInput(inputId="yaxis",  
                   label= "Y-axis Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="GGX_NGDP1"),
    selectizeInput(inputId="size",  
                   label= "Bubble Size Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="NGDPD1"
    ))
