
box(width=3, status="info", solidHeader=TRUE, 
    title="Select the Categories for the Scatter Plot",
    selectizeInput(inputId="WorldRegion1",
                   label="Select the Region of the World",
                   choices= c("Advanced Economies"=                                                "ADVANCED_EC",
                              "Euro Area"=                                                         "EURO_AREA",
                              "MAjor Advanced Economies (G7)" =                                    "M_ADVANCED_G7",
                              "Other Advanced (excluding G7 and euro Area)"=                       "OTHER_ADVANCED",    
                              "European Union"=                                                    "EUROPEAN_UNION",
                              "Emerging market and developing economies" =                         "EMERDEVP_EC",      
                              "Commonwealth and Independent States" =                              "COMMWIS",
                              "Emerging and developing Asia" =                                     "EMERDEVP_ASIA",
                              "ASEAN-5"=                                                           "ASEAN_5",
                              "Emerging and developing Europe"=                                    "EMERDEVP_EUROPE",
                              "Latin America and the Caribbean"=                                   "LATIN_AMERICA_CAB",
                              "Middle East, North Africa, Afghanistan, and Pakistan"=              "ME_NA_AF_PAK",
                              "Middle East and North Africa" =                                     "ME_NA",
                              "Sub-Saharan Africa"=                                               "SUBSAHARA_AF",
                              "All Countries"= "ALL"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="LATIN_AMERICA_CAB"),
    selectizeInput(inputId="xaxis",  
                   label= "X-axis Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="NGDPDPC1"),
    selectizeInput(inputId="yaxis",  
                   label= "Y-axis Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="GGX_NGDP1"),
    selectizeInput(inputId="size",  
                   label= "Bubble Size Variable:",
                   choices=c(#Balance of the government
                     "Gross domestic product, current prices, US dollars" =  "NGDPD1",
                     "Gross domestic product per capita, current prices" = "NGDPDPC1",
                     "Gross domestic product, constant prices, percent Change" = "NGDP_RPCH1", 
                     "Gross domestic product, current prices, PPP IUS" = "PPPGDP1",
                     "General government Revenue, percent of GDP" = "GGR_NGDP1",
                     "General government total expenditure, percent of GDP" = "GGX_NGDP1",
                     "General government net lending/borrowing, percent of GDP" = "GGXCNL_NGDP1",
                     "Total Investment, percent of GDP"= "NID_NGDP1",
                     "Gross National Savings, percent of GDP" = "NGSD_NGDP1",
                     "Output Gap, percent of potential GDP"= "NGAP_NPGDP1",
                     #Basic Economic Variables
                     "Employment, Milions" = "LE1",
                     "Population, Millions"= "LP1",
                     "Unemployment rate" = "LUR",
                     #External Sector
                     "Volume of exports of goods and services, percent change" = "TX_RPCH1",
                     "Volume of exports of goods, percent change" ="TXG_RPCH1", 
                     "Volume of imports of goods and services, percent change" = "TM_RPCH1",
                     "Volume of imports of goods, percent change" = "TMG_RPCH1", 
                     "Current account balance, US dollars"= "BCA1",
                     "Current account balance, percent of GDP" = "BCA_NGDPD1",
                     #Inflation 
                     "Inflation, average consumer prices, index"= "PCPI1",  
                     "Inflation, average consumer prices, percent change" = "PCPIPCH1",  
                     "Inflation, end of period consumer prices, index" = "PCPIE1", 
                     "Inflation, end of period consumer prices, percent change" = "PCPIEPCH1",  
                     #Conversion Rate
                     "Implied PPP conversion rate, National currency per current international dollar" = "PPPEX1",   
                     "Gross domestic product, current prices, Purchasing power parity; international dollars" = "PPPGDP1",  
                     "Gross domestic product per capita, current prices, Expressed in GDP in PPP dollars per person" = "PPPPC1",  
                     "Gross domestic product based on purchasing-power-parity (PPP) share of world total, percent" = "PPPSH1"),
                   multiple =TRUE, options = list(maxItems = 1L),
                   selected="NGDPD1"
    ),
    sliderInput("slider2",
                label=h3("Select the Range of Years"),
                min=1980, max=2022,
                value = c(2018, 2022)))
