
#data_unidad
tabPanel("Resumen General",
         fluidRow(
           headerPanel('Analisis Descriptivo de las Unidades de Compra'),
           column(
             width=9,
             fluidRow(box(width = 12,tabsetPanel(type = "tabs",
                                                 tabPanel(title = "Grafico por Unidades de Compra", 
                                                          highchartOutput(outputId ="adjudicaciones_unidades", height = "650px"),
                                                          h3("Tabla de Datos",align="center"),
                                                          DT::dataTableOutput("table888")),
                                                 tabPanel(title= "Vista Historica",
                                                          box(width=12, solidHeader = TRUE,status="info", title= "Seleccione la Unidad de Compra:",
                                                              selectInput(inputId="UNIDADES",
                                                                          label=NULL,
                                                                          choices=levels(as.factor(data_unidad$UNIDAD_COMPRA)),
                                                                          multiple =TRUE,
                                                                          selected="DIRECCION GENERAL DE COMUNICACION")), br(),
                                                          highchartOutput("historicos", height = "650px")))))),
           box(width=3, status="danger", solidHeader=TRUE, 
               title="Analisis de Genero",
               radioButtons(inputId = "GENERO", label="Seleccione el Genero:",
                            choices= c("Femenino"= "0",
                                       "Masculino, Femenino y No Especificado"="1")),
               h6("Notas:", br(), "- Todos los datos del aplicativo cambian al genero seleccionado",align="left")),
           box(width=3, status="primary", solidHeader = TRUE, 
               title= "Seleccione las Categorias de Interes:",
               selectInput(inputId="indicador",
                           label="Seleccione el indicador:",
                           choices= c("Total Adjudicado"= "total_adjudicado",
                                      "Cantidad de Contratos" ="contratos",
                                      "Proveedores Distintos Adjudicados"="proveedores_distintos_adjudicados"),
                           selected="total_adjudicado"),
               selectInput(inputId="gestion",
                           label="Seleccione los anos:",
                           choices= c("2016", "2017", "2018"),
                           multiple =TRUE,
                           selected="2018"),
               h6("Notas:", br(), "- Cuando se seleccionan varios anos las cifras en el aplicativo se presentan acumuladas", br(),"- El ano 2012.2 representa el periodo Septiembre- Diciembre 2012",
                  br (),"- ultima actualizacion de los datos: Septiembre 2018",align="left")),
           box(width=3, highchartOutput("grafico_pie"))))